server:
  port: 8080

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/missiondatabase?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Hongkong
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

#mybatis:
#  mapper-locations: classpath:mapping/*Mapper.xml
#  type-aliases-package: cn.gec.springbootssm.entity

#showSql
logging:
  level:
    cn:
      gec:
        springbootssm:
          mapper: debug

